apiVersion: apps/v1
kind: Deployment
metadata:
  name: asgbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asgbuggy
  template:
    metadata:
      labels:
        app: asgbuggy
    spec:
      containers:
      - name: asgbuggy
        image: 905418292159.dkr.ecr.ap-south-1.amazonaws.com/aws
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asgbuggy
    k8s-app: asgbuggy
  name: asgbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: asgbuggy
